name: Action for saltoris

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'master' 
      tag:
        description: 'Tag to use'
        required: true

jobs:
  Deployment-to-saltoris:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4

      # - name: Install dependencies
      #   run: npm install

      - name: Run build
        id: build
        run: |
          echo "hari"
          echo "::set-output name=build-status::${?}"

      - name: Change the remote 
        if: steps.build.outputs.build-status == '0'
        run: |
          apt-get update && apt-get install -y git
          git config --global user.name "Srihari62"
          git config --global user.email "srihari6281@gmail.com"
          git remote set-url origin https://github.com/Srihari62/gs-act-test.git 
          git add . 
          git commit -m "Code Transfer" 
          git push -u origin main
          q