name: Manual Push

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run:  pwd
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH }}
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: 'output'
          destination-github-username: 'Srihari62'
          destination-repository-name: 'gs-act-test'
          user-email: srihari6281@gmail.com
          target-branch: test
