name: Action for saltoris

on: 
  workflow_dispatch:
    inputs:
     branch:
        description: 'Branch'
        required: true
        default: 'master' 

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
         
      - name: change the remote 
        run: |
          git remote set-url origin https://Srihari62:${{secrets.PAT}}@github.com/Srihari62/git-actions.git
          git push



# steps:
#   add the new origin 
#   run the build step if success git push(adding a tag)