name: Action for saltoris

on: 
  workflow_dispatch:
    inputs:
     branch:
        description: 'Branch'
        required: true
        default: 'master' 

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
         
      - name: path 
        run: pwd

      - name: Set up Git
        run: |
          git config --global user.name 'Srihari62'
          git config --global user.email 'srihari6281@gmail.com'

      - name: Clone Second Org Repo
        run: |
          cd ..
          git clone https://${{secrets.PAT}}@github.com/Srihari62/gs-act-test.git
          pwd

      - name: Update Second Org Repo
        run: |
          cp -r /home/runner/work/gs-act-test/gs-act-test* /home/runner/work/git-actions/git-actions
          cd git-actions
          git add .
          git commit -m "Update with latest code from first org repo"
          git push  origin main
