name: Manual trigger

on:
  workflow_dispatch:

jobs:

  manual-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run manual task
        run: echo "This is a manual task"