name: Manual Push

on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creates output folder and remove markdown
        run:  |
              mkdir output
              cp -r posts output
      - name: Pushes to public repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.PAT }}
        with:
          source-directory: output/
          destination-github-username: 'Srihari62'
          destination-repository-name: 'gs-act-test'
          user-email: srihari6281@gmail.com.com
          commit-message: pushed from $GITHUB_REF
          target-branch: git