name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  automatic-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run automatic build
        run: echo "run build done"

      # Add more steps as needed for manual tasks.
