name: Run Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run test
        run: echo "Hello test"
      - name: Set status checks
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: github.sha,
              state: 'success', // or 'failure' based on your test results
              context: 'Your Context Name',
              description: 'Your description',
            })
